name: Mobile Test Automation - Calendar App

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Choose the test suite to run'
        required: true
        default: 'CalendarAppRegression'
        type: choice
        options:
          - CalendarAppRegression
          - CalendarAppSmoke

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run tests
        run: mvn test -DtestSuite=${{ inputs.test_suite }}.xml